#!/usr/bin/env node
/**
 * Commit-time enforcement for the two AGENTS.md rules that cannot be
 * expressed as lint rules:
 *
 *   §7  400-line hard cap. ESLint warns at 250; this fails at 400.
 *   §6  components/ui/ is generated by shadcn and must never be edited.
 *       Adding a new generated component is fine; changing one is not.
 *
 * Checks the staged blob, not the working tree, so a partially staged file
 * is judged on what is actually being committed.
 */
import { execFileSync } from "node:child_process";

const HARD_CAP = 400;
const UI_DIR = "apps/web/src/components/ui/";
const CODE = /\.(ts|tsx|js|jsx|mjs|cjs)$/;

const git = (args) => execFileSync("git", args, { encoding: "utf8" });

/** Staged changes as [status, path] pairs, paths relative to this directory. */
function stagedChanges() {
  const out = git(["diff", "--cached", "--name-status", "--relative"]).trim();
  if (!out) return [];
  return out.split("\n").map((line) => {
    const [status, ...rest] = line.split("\t");
    // Renames report as "R100\told\tnew" — the new path is what we check.
    // Kept as the full status (not just status[0]) so a pure rename (R100)
    // can be told apart from a rename that also changed content (R<100).
    return [status, rest[rest.length - 1]];
  });
}

function stagedLineCount(path) {
  try {
    return git(["show", `:./${path}`]).split("\n").length;
  } catch {
    return 0; // Deleted, or unreadable — nothing to measure.
  }
}

const errors = [];

for (const [status, path] of stagedChanges()) {
  const normalised = path.replace(/\\/g, "/");
  // "A" is a fresh add; "R100" is a pure rename (git found the old and new
  // blob byte-identical) — both leave the generated file's content untouched.
  const isAllowedForUiDir = status === "A" || status === "R100";

  if (normalised.startsWith(UI_DIR) && !isAllowedForUiDir) {
    errors.push(
      `${normalised} — generated shadcn file was ${status[0] === "D" ? "deleted" : "modified"}.\n` +
        `    AGENTS.md §6: wrap it in components/common/ instead. Re-running\n` +
        `    'npx shadcn add' must produce no diff here.`,
    );
    continue;
  }

  if (status[0] !== "D" && CODE.test(normalised)) {
    const lines = stagedLineCount(normalised);
    if (lines > HARD_CAP) {
      errors.push(
        `${normalised} — ${lines} lines, over the ${HARD_CAP}-line hard cap.\n` +
          `    AGENTS.md §7: split it by responsibility, not by line count.`,
      );
    }
  }
}

if (errors.length > 0) {
  console.error(`\nCommit blocked by ${errors.length} rule violation(s):\n`);
  for (const error of errors) console.error(`  ${error}\n`);
  process.exit(1);
}
